# Seattle Building Energy Forecasting

URL: https://www.kaggle.com/city-of-seattle/sea-building-energy-benchmarking

## Notebook nÂ°1 - Data Cleaning - Part 1

Objective : Create a unique dataframe from the 2015 and 2016 data

#### Import librairies

In [1]:
from ast import literal_eval
import pickle
import pandas as pd

#### Display Settings

In [2]:
pd.options.display.max_rows = 100
pd.options.display.max_columns = 100

#### Import data

In [3]:
df2015 = pd.read_csv("data/2015-building-energy-benchmarking.csv")
df2016 = pd.read_csv("data/2016-building-energy-benchmarking.csv")

#### Shape

In [4]:
print(df2015.shape)
print(df2016.shape)

(3340, 47)
(3376, 46)

#### Preview

In [5]:
# 2015
df2015.head()

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,TaxParcelIdentificationNumber,Location,CouncilDistrictCode,Neighborhood,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),ListOfAllPropertyUseTypes,LargestPropertyUseType,LargestPropertyUseTypeGFA,SecondLargestPropertyUseType,SecondLargestPropertyUseTypeGFA,ThirdLargestPropertyUseType,ThirdLargestPropertyUseTypeGFA,YearsENERGYSTARCertified,ENERGYSTARScore,SiteEUI(kBtu/sf),SiteEUIWN(kBtu/sf),SourceEUI(kBtu/sf),SourceEUIWN(kBtu/sf),SiteEnergyUse(kBtu),SiteEnergyUseWN(kBtu),SteamUse(kBtu),Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),OtherFuelUse(kBtu),GHGEmissions(MetricTonsCO2e),GHGEmissionsIntensity(kgCO2e/ft2),DefaultData,Comment,ComplianceStatus,Outlier,2010 Census Tracts,Seattle Police Department Micro Community Policing Plan Areas,City Council Districts,SPD Beats,Zip Codes
0,1,2015,NonResidential,Hotel,MAYFLOWER PARK HOTEL,659000030,"{'latitude': '47.61219025', 'human_address': '...",7,DOWNTOWN,1927,1,12.0,88434,0,88434,Hotel,Hotel,88434.0,NaN,NaN,NaN,NaN,NaN,65.0,78.9,80.3,173.5,175.1,6981428.0,7097539.0,2023032.0,1080307.0,3686160.0,12724.0,1272388.0,0.0,249.43,2.64,No,NaN,Compliant,NaN,NaN,14.0,NaN,31.0,18081
1,2,2015,NonResidential,Hotel,PARAMOUNT HOTEL,659000220,"{'latitude': '47.61310583', 'human_address': '...",7,DOWNTOWN,1996,1,11.0,103566,15064,88502,"Hotel, Parking, Restaurant",Hotel,83880.0,Parking,15064.0,Restaurant,4622.0,NaN,51.0,94.4,99.0,191.3,195.2,8354235.0,8765788.0,0.0,1144563.0,3905411.0,44490.0,4448985.0,0.0,263.51,2.38,No,NaN,Compliant,NaN,NaN,14.0,NaN,31.0,18081
2,3,2015,NonResidential,Hotel,WESTIN HOTEL,659000475,"{'latitude': '47.61334897', 'human_address': '...",7,DOWNTOWN,1969,1,41.0,961990,0,961990,"Hotel, Parking, Swimming Pool",Hotel,757243.0,Parking,100000.0,Swimming Pool,0.0,NaN,18.0,96.6,99.7,242.7,246.5,73130656.0,75506272.0,19660404.0,14583930.0,49762435.0,37099.0,3709900.0,0.0,2061.48,1.92,Yes,NaN,Compliant,NaN,NaN,56.0,NaN,31.0,18081
3,5,2015,NonResidential,Hotel,HOTEL MAX,659000640,"{'latitude': '47.61421585', 'human_address': '...",7,DOWNTOWN,1926,1,10.0,61320,0,61320,Hotel,Hotel,61320.0,NaN,NaN,NaN,NaN,NaN,1.0,460.4,462.5,636.3,643.2,28229320.0,28363444.0,23458518.0,811521.0,2769023.0,20019.0,2001894.0,0.0,1936.34,31.38,No,NaN,Compliant,High Outlier,NaN,56.0,NaN,31.0,18081
4,8,2015,NonResidential,Hotel,WARWICK SEATTLE HOTEL,659000970,"{'latitude': '47.6137544', 'human_address': '{...",7,DOWNTOWN,1980,1,18.0,119890,12460,107430,"Hotel, Parking, Swimming Pool",Hotel,123445.0,Parking,68009.0,Swimming Pool,0.0,NaN,67.0,120.1,122.1,228.8,227.1,14829099.0,15078243.0,0.0,1777841.0,6066245.0,87631.0,8763105.0,0.0,507.70,4.02,No,NaN,Compliant,NaN,NaN,56.0,NaN,31.0,19576

In [6]:
# 2016
df2016.head()

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,CouncilDistrictCode,Neighborhood,Latitude,Longitude,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),ListOfAllPropertyUseTypes,LargestPropertyUseType,LargestPropertyUseTypeGFA,SecondLargestPropertyUseType,SecondLargestPropertyUseTypeGFA,ThirdLargestPropertyUseType,ThirdLargestPropertyUseTypeGFA,YearsENERGYSTARCertified,ENERGYSTARScore,SiteEUI(kBtu/sf),SiteEUIWN(kBtu/sf),SourceEUI(kBtu/sf),SourceEUIWN(kBtu/sf),SiteEnergyUse(kBtu),SiteEnergyUseWN(kBtu),SteamUse(kBtu),Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
0,1,2016,NonResidential,Hotel,Mayflower park hotel,405 Olive way,Seattle,WA,98101.0,0659000030,7,DOWNTOWN,47.61220,-122.33799,1927,1.0,12,88434,0,88434,Hotel,Hotel,88434.0,NaN,NaN,NaN,NaN,NaN,60.0,81.699997,84.300003,182.500000,189.000000,7226362.5,7456910.0,2003882.00,1.156514e+06,3946027.0,12764.52930,1276453.0,False,NaN,Compliant,NaN,249.98,2.83
1,2,2016,NonResidential,Hotel,Paramount Hotel,724 Pine street,Seattle,WA,98101.0,0659000220,7,DOWNTOWN,47.61317,-122.33393,1996,1.0,11,103566,15064,88502,"Hotel, Parking, Restaurant",Hotel,83880.0,Parking,15064.0,Restaurant,4622.0,NaN,61.0,94.800003,97.900002,176.100006,179.399994,8387933.0,8664479.0,0.00,9.504252e+05,3242851.0,51450.81641,5145082.0,False,NaN,Compliant,NaN,295.86,2.86
2,3,2016,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,Seattle,WA,98101.0,0659000475,7,DOWNTOWN,47.61393,-122.33810,1969,1.0,41,956110,196718,759392,Hotel,Hotel,756493.0,NaN,NaN,NaN,NaN,NaN,43.0,96.000000,97.699997,241.899994,244.100006,72587024.0,73937112.0,21566554.00,1.451544e+07,49526664.0,14938.00000,1493800.0,False,NaN,Compliant,NaN,2089.28,2.19
3,5,2016,NonResidential,Hotel,HOTEL MAX,620 STEWART ST,Seattle,WA,98101.0,0659000640,7,DOWNTOWN,47.61412,-122.33664,1926,1.0,10,61320,0,61320,Hotel,Hotel,61320.0,NaN,NaN,NaN,NaN,NaN,56.0,110.800003,113.300003,216.199997,224.000000,6794584.0,6946800.5,2214446.25,8.115253e+05,2768924.0,18112.13086,1811213.0,False,NaN,Compliant,NaN,286.43,4.67
4,8,2016,NonResidential,Hotel,WARWICK SEATTLE HOTEL (ID8),401 LENORA ST,Seattle,WA,98121.0,0659000970,7,DOWNTOWN,47.61375,-122.34047,1980,1.0,18,175580,62000,113580,"Hotel, Parking, Swimming Pool",Hotel,123445.0,Parking,68009.0,Swimming Pool,0.0,NaN,75.0,114.800003,118.699997,211.399994,215.600006,14172606.0,14656503.0,0.00,1.573449e+06,5368607.0,88039.98438,8803998.0,False,NaN,Compliant,NaN,505.01,2.88

#### Functions

In [7]:
def f1_not_f2(f1, f2):
    col_warning = []
    for col in f1.columns:
        if col not in f2.columns:
            col_warning.append(col)
    
    return col_warning

#### NaN by feature

In [8]:
# 2015
pd.DataFrame(round(df2015.isna().sum().sort_values(ascending=False) / len(df2015),3))

                                                        0
Comment                                             0.996
Outlier                                             0.975
YearsENERGYSTARCertified                            0.967
City Council Districts                              0.936
2010 Census Tracts                                  0.933
ThirdLargestPropertyUseTypeGFA                      0.832
ThirdLargestPropertyUseType                         0.832
SecondLargestPropertyUseTypeGFA                     0.533
SecondLargestPropertyUseType                        0.533
ENERGYSTARScore                                     0.234
LargestPropertyUseTypeGFA                           0.041
LargestPropertyUseType                              0.041
ListOfAllPropertyUseTypes                           0.038
SiteEnergyUse(kBtu)                                 0.003
SiteEUI(kBtu/sf)                                    0.003
SiteEUIWN(kBtu/sf)                                  0.003
SourceEUI(kBtu/sf)                                  0.003
SourceEUIWN(kBtu/sf)                                0.003
SiteEnergyUseWN(kBtu)                               0.003
NaturalGas(therms)                                  0.003
GHGEmissions(MetricTonsCO2e)                        0.003
OtherFuelUse(kBtu)                                  0.003
NaturalGas(kBtu)                                    0.003
GHGEmissionsIntensity(kgCO2e/ft2)                   0.003
Electricity(kBtu)                                   0.003
Electricity(kWh)                                    0.003
SteamUse(kBtu)                                      0.003
NumberofFloors                                      0.002
SPD Beats                                           0.001
Seattle Police Department Micro Community Polic...  0.001
TaxParcelIdentificationNumber                       0.001
DefaultData                                         0.000
CouncilDistrictCode                                 0.000
DataYear                                            0.000
BuildingType                                        0.000
PrimaryPropertyType                                 0.000
PropertyName                                        0.000
Location                                            0.000
Zip Codes                                           0.000
Neighborhood                                        0.000
YearBuilt                                           0.000
NumberofBuildings                                   0.000
PropertyGFATotal                                    0.000
PropertyGFAParking                                  0.000
PropertyGFABuilding(s)                              0.000
ComplianceStatus                                    0.000
OSEBuildingID                                       0.000

In [9]:
# 2016
pd.DataFrame(round(df2016.isna().sum().sort_values(ascending=False) / len(df2015),3))

                                     0
Comments                         1.011
Outlier                          1.001
YearsENERGYSTARCertified         0.975
ThirdLargestPropertyUseType      0.832
ThirdLargestPropertyUseTypeGFA   0.832
SecondLargestPropertyUseType     0.508
SecondLargestPropertyUseTypeGFA  0.508
ENERGYSTARScore                  0.252
LargestPropertyUseTypeGFA        0.006
LargestPropertyUseType           0.006
ZipCode                          0.005
SourceEUI(kBtu/sf)               0.003
ListOfAllPropertyUseTypes        0.003
TotalGHGEmissions                0.003
GHGEmissionsIntensity            0.003
NaturalGas(therms)               0.003
SourceEUIWN(kBtu/sf)             0.003
NaturalGas(kBtu)                 0.003
SteamUse(kBtu)                   0.003
Electricity(kWh)                 0.003
Electricity(kBtu)                0.003
NumberofBuildings                0.002
SiteEUI(kBtu/sf)                 0.002
SiteEUIWN(kBtu/sf)               0.002
SiteEnergyUseWN(kBtu)            0.002
SiteEnergyUse(kBtu)              0.001
TaxParcelIdentificationNumber    0.000
DataYear                         0.000
BuildingType                     0.000
PrimaryPropertyType              0.000
PropertyName                     0.000
Address                          0.000
City                             0.000
State                            0.000
ComplianceStatus                 0.000
CouncilDistrictCode              0.000
DefaultData                      0.000
Neighborhood                     0.000
Latitude                         0.000
Longitude                        0.000
YearBuilt                        0.000
NumberofFloors                   0.000
PropertyGFATotal                 0.000
PropertyGFAParking               0.000
PropertyGFABuilding(s)           0.000
OSEBuildingID                    0.000

#### Total rows 2015 + 2016

In [10]:
pd.concat([df2015, df2016], sort=False).shape

(6716, 56)

#### Total unique rows 2015 + 2016

In [11]:
pd.concat([df2015, df2016], sort=False).drop_duplicates().shape

(6716, 56)

#### Columns existing in 2015 but not in 2016

In [12]:
f1_not_f2(df2015, df2016)

['Location',
 'OtherFuelUse(kBtu)',
 'GHGEmissions(MetricTonsCO2e)',
 'GHGEmissionsIntensity(kgCO2e/ft2)',
 'Comment',
 '2010 Census Tracts',
 'Seattle Police Department Micro Community Policing Plan Areas',
 'City Council Districts',
 'SPD Beats',
 'Zip Codes']

#### Columns existing in 2016 but not in 2015

In [13]:
f1_not_f2(df2016, df2015)

['Address',
 'City',
 'State',
 'ZipCode',
 'Latitude',
 'Longitude',
 'Comments',
 'TotalGHGEmissions',
 'GHGEmissionsIntensity']

#### Flatten the "Location" feature in the 2015 dataframe

In [14]:
# Flatten the "Location" feature
df2015["Location"] = df2015["Location"].apply(literal_eval)

# Extract features
df2015["Latitude"] = df2015["Location"].apply(lambda x: x["latitude"])
df2015["Longitude"] = df2015["Location"].apply(lambda x: x["longitude"])
df2015["human_address"] = df2015["Location"].apply(lambda x: x["human_address"])

# Flatten the "Human Address" feature
df2015["human_address"] = df2015["human_address"].apply(literal_eval)

# Extract features
df2015["Address"] = df2015["human_address"].apply(lambda x: x["address"])
df2015["City"] = df2015["human_address"].apply(lambda x: x["city"])
df2015["State"] = df2015["human_address"].apply(lambda x: x["state"])
df2015["ZipCode"] = df2015["human_address"].apply(lambda x: x["zip"])

# Remove useless columns
df2015.drop(["Location", "human_address"], axis=1, inplace=True)

#### Columns existing in 2015 but not in 2016

In [15]:
f1_not_f2(df2015, df2016)

['OtherFuelUse(kBtu)',
 'GHGEmissions(MetricTonsCO2e)',
 'GHGEmissionsIntensity(kgCO2e/ft2)',
 'Comment',
 '2010 Census Tracts',
 'Seattle Police Department Micro Community Policing Plan Areas',
 'City Council Districts',
 'SPD Beats',
 'Zip Codes']

#### Columns existing in 2016 but not in 2015

In [16]:
f1_not_f2(df2016, df2015)

['Comments', 'TotalGHGEmissions', 'GHGEmissionsIntensity']

#### Rename some columns to match

In [17]:
df2016.rename(columns={"Comments": "Comment"}, inplace=True)

df2015.rename(columns={
    "GHGEmissions(MetricTonsCO2e)": "TotalGHGEmissions",
    "GHGEmissionsIntensity(kgCO2e/ft2)": "GHGEmissionsIntensity"}, inplace=True)

#### Columns existing in 2015 but not in 2016

In [18]:
f1_not_f2(df2015, df2016)

['OtherFuelUse(kBtu)',
 '2010 Census Tracts',
 'Seattle Police Department Micro Community Policing Plan Areas',
 'City Council Districts',
 'SPD Beats',
 'Zip Codes']

#### Let's have a look at this features

In [19]:
print(df2015["OtherFuelUse(kBtu)"].isna().sum())
df2015["OtherFuelUse(kBtu)"].describe()

10

count    3.330000e+03
mean     7.142301e+03
std      1.962790e+05
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      8.269669e+06
Name: OtherFuelUse(kBtu), dtype: float64

In [20]:
print(df2015["2010 Census Tracts"].isna().sum())
df2015["2010 Census Tracts"].describe()

3116

count    224.000000
mean     123.062500
std        5.812128
min      116.000000
25%      117.000000
50%      123.000000
75%      125.500000
max      135.000000
Name: 2010 Census Tracts, dtype: float64

In [21]:
print(df2015["Seattle Police Department Micro Community Policing Plan Areas"].isna().sum())
df2015["Seattle Police Department Micro Community Policing Plan Areas"].describe()

2

count    3338.000000
mean       32.380168
std        19.907567
min         1.000000
25%        14.000000
50%        33.000000
75%        50.000000
max        61.000000
Name: Seattle Police Department Micro Community Policing Plan Areas, dtype: float64

In [22]:
print(df2015["City Council Districts"].isna().sum())
df2015["City Council Districts"].describe()

3127

count    213.000000
mean       1.347418
std        0.477272
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        2.000000
Name: City Council Districts, dtype: float64

In [23]:
print(df2015["SPD Beats"].isna().sum())
df2015["SPD Beats"].describe()

2

count    3338.000000
mean       24.825644
std        15.006287
min         1.000000
25%        10.000000
50%        26.000000
75%        38.000000
max        51.000000
Name: SPD Beats, dtype: float64

In [24]:
print(df2015["Zip Codes"].isna().sum())
df2015["Zip Codes"].describe()

0

count     3340.000000
mean     18786.680240
std        588.604192
min      17916.000000
25%      18379.000000
50%      18390.000000
75%      19576.000000
max      19584.000000
Name: Zip Codes, dtype: float64

#### Now we remove them

In [25]:
df2015.drop(f1_not_f2(df2015, df2016), axis=1, inplace=True)

#### And we concatenate the two dataframes

In [26]:
df_final = pd.concat([df2015, df2016], sort=False)

In [27]:
df_final.shape

(6716, 46)

#### Save the final dataframe

In [28]:
with open("data/part1.pkl", "wb") as f:
    my_pickle = pickle.Pickler(f)
    my_pickle.dump(df_final)